/** Attack strategy catalog. Tools tag coverage automatically; agents may also cite ids in log_hypothesis/record_finding. */
export const STRATEGIES = {
  'size.sweep': 'Sweep all viewport widths (sweep_viewports)',
  'size.breakpoint-edges': 'Resize to N-1/N/N+1 around CSS breakpoints',
  'size.resize-with-overlay': 'Resize while a modal/menu/popover is open',
  'size.orientation': 'Flip phone portrait <-> landscape',
  'content.long-word': 'Long unbroken word in inputs',
  'content.long-text': 'Long sentence in inputs',
  'content.huge-paste': '5k-char paste',
  'content.intl': 'Emoji / CJK / RTL / zalgo input',
  'content.empty': 'Empty or whitespace-only input, submit',
  'content.label-mutation': 'Longer labels via mutate_text (translation stress)',
  'content.font-scale': '200% text size',
  'content.zoom': 'Browser zoom 50%-300%',
  'chaos.rapid-click': 'Rapid double/triple clicks',
  'chaos.click-while-loading': 'Click while content is loading',
  'chaos.multi-open': 'Open several menus/popovers at once',
  'chaos.hover-transition': 'Hover during transitions / move pointer across gaps',
  'chaos.scroll-extremes': 'Scroll to top/bottom/far edges',
  'chaos.keyboard': 'Keyboard-only: Tab/Shift-Tab/Enter/Escape, focus visibility & traps',
  'nav.back-forward': 'Back/forward in the middle of a flow',
  'nav.reload-mid-flow': 'Reload mid-form / mid-flow',
  'nav.deep-link': 'Deep-link straight to an inner route',
  'nav.repeat-flow': 'Run the same flow twice',
  'env.offline': 'Go offline / slow 3G',
  'env.block-resources': 'Block fonts/images (fallback reflow)',
  'env.dark-mode': 'Dark color scheme',
  'env.reduced-motion': 'Reduced motion',
  'env.dpr': 'Device pixel ratio 1/2/3',
  'data.empty-state': 'Empty lists / no results',
  'data.many-items': 'Many items (add until crowded)',
  'data.error-state': 'Error states (blocked mutations return 503)',
} as const;
export type StrategyId = keyof typeof STRATEGIES;
export const STRATEGY_IDS = Object.keys(STRATEGIES) as StrategyId[];
