import { expect, it, vi } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, readdirSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const spawn = vi.hoisted(() => vi.fn(() => ({ pid: process.pid, unref: vi.fn(), on: vi.fn() })));
const runAgent = vi.hoisted(() => vi.fn(async (_options: { prompt: string }) => ({ ok: true, text: 'Here are the findings', error: null })));
vi.mock('../../src/llm/runner.ts', () => ({ runAgent }));
vi.mock('node:child_process', () => ({ spawn }));

it('continues a finished job without creating a job or replacing its history', async () => {
  const root = mkdtempSync(join(tmpdir(), 'conversation-'));
  process.env.BUGBASH_WEB_JOBS = root;
  const dir = join(root, 'explore-existing');
  mkdirSync(dir);
  const job = { id: 'explore-existing', kind: 'explore', state: 'succeeded', pid: 0, options: {}, started_at: 'original-start', ended_at: 'end', run_dir: null, finding_ids: [], error: null };
  writeFileSync(join(dir, 'status.json'), JSON.stringify(job));
  writeFileSync(join(dir, 'events.jsonl'), '{"msg":"original activity"}\n');
  const { followupJob } = await import('../server/jobs.ts');
  const result = followupJob(job.id, 'Explain the findings');
  expect(result.id).toBe(job.id);
  expect(result.started_at).toBe('original-start');
  expect(result.state).toBe('running');
  expect(readdirSync(root)).toEqual([job.id]);
  expect(readFileSync(join(dir, 'events.jsonl'), 'utf8')).toContain('original activity');
  expect(readFileSync(join(dir, 'messages.jsonl'), 'utf8')).toContain('Explain the findings');
  expect(spawn.mock.calls[0]).toBeDefined();
  expect(() => followupJob(job.id, 'Duplicate restart')).toThrow('running');
  process.env.BUGBASH_JOB_DIR = root;
  const { continueConversation } = await import('../server/jobConversation.ts');
  await continueConversation(dir);
  expect(runAgent).toHaveBeenCalledOnce();
  expect(runAgent.mock.calls[0][0].prompt).toContain('Explain the findings');
  expect(runAgent.mock.calls[0][0].prompt).toContain('original activity');
  expect(readdirSync(root)).toEqual([job.id]);
  const final = JSON.parse(readFileSync(join(dir, 'status.json'), 'utf8'));
  expect(final.id).toBe(job.id);
  expect(final.state).toBe('succeeded');
  expect(readFileSync(join(dir, 'events.jsonl'), 'utf8')).toContain('Here are the findings');
});
